## Problem 3. SVM (25 points)

In this section we have two exercises:
1. Implement the SVM Kernels.
2. Implement the multiclass C-SVM.

In [8]:
import sys
print(sys.executable)

/Users/ddigimon/anaconda3/envs/TC-GPU/bin/python


In [9]:
from sklearn.datasets import load_iris
import numpy as np
import sklearn
from sklearn.model_selection import train_test_split
import cvxopt
from scipy.stats import logistic
from sklearn.metrics import accuracy_score

iris = load_iris()
data_set = iris.data
labels = iris.target


print("DONE")

DONE


### 3.1 SVM Kernels (15 points)
In practice, SVM algorithm is implemented with a kernel that transforms an input data space into the required form. SVM uses a technique called the kernel trick in which the kernel transforms the data from a low-dimensional input space into a higher-dimensional space. In other words, kernel converts non-separable problems into separable problems by adding more dimensions to it. It makes SVM more powerful, flexible and accurate. The following are some of the types of kernels used by SVM.
### Linear Kernel
It can be used as a dot product between any two observations. The formula of linear kernel is as below:
$$ K(x,x_i)=sum(x∗x_i)$$
From the above formula, we can see that the product between two vectors say $𝑥$ & $𝑥_𝑖$ is the sum of the multiplication of each pair of input values.
### Polynomial Kernel
It is more generalized form of linear kernel and distinguish curved or nonlinear input space. Following is the formula for polynomial kernel：
$$k(x,x_i)=sum(x∗x_i)^d$$
Here $d$ is the degree of polynomial, which we need to specify manually in the learning algorithm.
### Radial Basis Function (RBF) Kernel
RBF kernel, mostly used in SVM classification, maps input space in indefinite dimensional space. Following formula explains it mathematically:
$$k(x,x_i)=exp(−gamma∗||x−x_i||^2)$$
Here, gamma ranges from 0 to 1. We need to manually specify it in the learning algorithm. A good default value of gamma is 0.1.
As we implemented SVM for linearly separable data, we can implement it in Python for the data that is not linearly separable. It can be done by using kernels.
### Implement
You need to complete the ``build_kernel`` function 

In [10]:
# Y is a variable, which the user has to define. 
#Similarly the user has to define d, which is the dimension of the polynomial kernel

train_data_set, test_data_set, train_labels, test_labels = train_test_split(
    data_set, labels, test_size=0.2, random_state=15)

# print(data_set)

def build_kernel_first(data_set, d, Y, kernel_type = 'rbf'):
    kernel = np.dot(data_set, Y.T)
    if kernel_type == 'rbf':
        # put your code here
        ##########################################################
        n=len(data_set)
        for j in range(n):
            for i in range(n):
                kernel[i,j]=np.exp(-0.1*np.sum(np.power((data_set[i,:]-Y[j,:]),2)))

        
        
        
        
        ##########################################################
    elif kernel_type == 'poly':
        data_set_features = np.array(data_set).shape[1]
        Y_features = np.array(Y).shape[1]
        
        if data_set_features != Y_features:
            n = data_set_features - Y_features
            print("Warning ! Wrong shape of Y.",n,"extra columns of zeros where automatically added to Y in place of missing features!")
            print("You should add more features to Y data_set. Currently there are only",Y_features,"features!\n")
            b = np.zeros((np.array(Y).shape[0], Y_features+n))
            b[:,:-n] = Y
            Y=b
        # put your code here
        #########################################################
        
        kernel = np.power(np.dot(data_set, Y.T),d)
        
        
        
        ##########################################################
    return kernel


#Here comparing linear_kernel with poly_kernel with parameters Y=train_data_set and d=1.
#The output should be the should be the same.



print("-------------------------------------------------------")
print("Poly kernel with parameters Y=train_data_set and d=1.\n")
poly_kernel = build_kernel_first(train_data_set, d=1, Y=train_data_set, kernel_type='poly')
print(poly_kernel)

print("-------------------------------------------------------")
print("Linear kernel with parameter Y=train_data_set.\n")
linear_kernel = build_kernel_first(train_data_set, d=1, Y=train_data_set, kernel_type='linear')
print(linear_kernel)

print("\n-------------------------------------------------------")
print("Test of error warning:")
Y = np.ones(shape = [80, 2])
poly_kernel = build_kernel_first(train_data_set, d=1, Y=Y, kernel_type='poly')
print(poly_kernel)

-------------------------------------------------------
Poly kernel with parameters Y=train_data_set and d=1.

[[40.26 54.6  48.04 ... 45.6  49.37 53.34]
 [54.6  96.58 83.2  ... 80.79 85.34 94.04]
 [48.04 83.2  72.2  ... 70.05 73.93 81.  ]
 ...
 [45.6  80.79 70.05 ... 68.09 71.71 78.62]
 [49.37 85.34 73.93 ... 71.71 75.79 83.05]
 [53.34 94.04 81.   ... 78.62 83.05 91.62]]
-------------------------------------------------------
Linear kernel with parameter Y=train_data_set.

[[40.26 54.6  48.04 ... 45.6  49.37 53.34]
 [54.6  96.58 83.2  ... 80.79 85.34 94.04]
 [48.04 83.2  72.2  ... 70.05 73.93 81.  ]
 ...
 [45.6  80.79 70.05 ... 68.09 71.71 78.62]
 [49.37 85.34 73.93 ... 71.71 75.79 83.05]
 [53.34 94.04 81.   ... 78.62 83.05 91.62]]

-------------------------------------------------------
Test of error warning:


ValueError: shapes (120,4) and (2,80) not aligned: 4 (dim 1) != 2 (dim 0)



### 3.2 Implement a multiclass C-SVM (10 points)

Use the IRIS dataset loaded above to build a multiclass C-SVM classifier. The implementation needs a function that returns the proper dataset to be used for the prediction. You need to implement:
- ``choose_set_for_label``

In [11]:
def choose_set_for_label(data_set1, labels1, treshold, other):
    
    
    '''
        You need to use "train_test_split" function to divide data_set1 (test_ size=0.2, random_ state=15), And compare the label with the threshold
        （< treshold = -1，>= treshold =1）
    '''
    #put your code here
    ##########################################################
    train_data_set, test_data_set, train_labels, test_labels = train_test_split(data_set, labels, test_size=0.2, random_state=15)
    print(train_labels)
    
    
    
    print(np.shape(train_data_set))
    print(np.shape(test_data_set))
    print(np.shape(train_labels))
    print(np.shape(test_labels))
    train_data_set=np.delete(train_data_set,np.where(train_labels==other),axis=0)
    test_data_set=np.delete(test_data_set,np.where(test_labels==other),axis=0)
    train_labels=np.delete(train_labels,np.where(train_labels==other),axis=0)
    test_labels=np.delete(test_labels,np.where(test_labels==other),axis=0) 
#     for i in range(len(train_labels)):
#         if train_labels[i]<treshold:
#             train_labels[i]=-1
#         else:
#             train_labels[i]=1
#     for i in range(len(test_labels)):
#         if test_labels[i]<treshold:
#             test_labels[i]=-1
#         else:
#             test_labels[i]=1
    train_labels[train_labels<treshold]=-1
    train_labels[train_labels>=treshold]=1
    test_labels[test_labels<treshold]=-1
    test_labels[test_labels>=treshold]=1
    print(np.shape(train_data_set))
    print(np.shape(test_data_set))
    print(np.shape(train_labels))
    print(np.shape(test_labels))
    
    
    print(train_labels)
    
    
    ##########################################################
    return train_data_set, test_data_set, train_labels, test_labels
print("DONE")

DONE


Run the following code to test your implementation:

In [12]:
def build_kernel(data_set, kernel_type='rbf'):
    kernel = np.dot(data_set, data_set.T)
    if kernel_type == 'rbf':
        sigma = 1.0
        objects_count = len(data_set)
        b = np.ones((len(data_set), 1))
        kernel -= 0.5 * (np.dot((np.diag(kernel)*np.ones((1, objects_count))).T, b.T)
                         + np.dot(b, (np.diag(kernel) * np.ones((1, objects_count))).T.T))
        kernel = np.exp(kernel / (2. * sigma ** 2))
    return kernel


def train(train_data_set, train_labels, kernel_type='linear', C=10, threshold=1e-5):
    kernel = build_kernel(train_data_set, kernel_type=kernel_type)

    objects_count = len(train_labels)
    
    P = train_labels * train_labels.transpose() * kernel
    q = -np.ones((objects_count, 1))
    G = np.concatenate((np.eye(objects_count), -np.eye(objects_count)))
    h = np.concatenate((C * np.ones((objects_count, 1)), np.zeros((objects_count, 1))))

    A = train_labels.reshape(1, objects_count)
    A = A.astype(float)
    b = 0.0

    sol = cvxopt.solvers.qp(cvxopt.matrix(P), cvxopt.matrix(q), cvxopt.matrix(G), cvxopt.matrix(h), cvxopt.matrix(A), cvxopt.matrix(b))

    lambdas = np.array(sol['x'])

    support_vectors_id = np.where(lambdas > threshold)[0]
    vector_number = len(support_vectors_id)
    support_vectors = train_data_set[support_vectors_id, :]

    lambdas = lambdas[support_vectors_id]
    targets = train_labels[support_vectors_id]

    b = np.sum(targets)
    for n in range(vector_number):
        b -= np.sum(lambdas * targets * np.reshape(kernel[support_vectors_id[n], support_vectors_id], (vector_number, 1)))
    b /= len(lambdas)

    return lambdas, support_vectors, support_vectors_id, b, targets, vector_number



def classify_rbf(test_data_set, train_data_set, lambdas, targets, b, vector_number, support_vectors, support_vectors_id):
    kernel = np.dot(test_data_set, support_vectors.T)
    sigma = 1.0
    #K = np.dot(test_data_set, support_vectors.T)
    #kernel = build_kernel(train_data_set, kernel_type='rbf')
    c = (1. / sigma * np.sum(test_data_set ** 2, axis=1) * np.ones((1, np.shape(test_data_set)[0]))).T
    c = np.dot(c, np.ones((1, np.shape(kernel)[1])))
    #aa = np.dot((np.diag(K)*np.ones((1,len(test_data_set)))).T[support_vectors_id], np.ones((1, np.shape(K)[0]))).T
    sv = (np.diag(np.dot(train_data_set, train_data_set.T))*np.ones((1,len(train_data_set)))).T[support_vectors_id]
    aa = np.dot(sv,np.ones((1,np.shape(kernel)[0]))).T
    kernel = kernel - 0.5 * c - 0.5 * aa
    kernel = np.exp(kernel / (2. * sigma ** 2))

    y = np.zeros((np.shape(test_data_set)[0], 1))
    for j in range(np.shape(test_data_set)[0]):
        for i in range(vector_number):
            y[j] += lambdas[i] * targets[i] * kernel[j, i]
        y[j] += b
    return np.sign(y)

In [13]:
treshold=[1,1.5,2]
#1->(Setosa vs Versicolor), 1.5->(Setosa vs Virginica), 2->(Virginica vs Versicolor)
other=[2,1,0] #which class is excluded, we consider pairs only
names=['Setosa vs VersiColor', 'Setosa vs Virginica', 'Virginica vs Versicolor']

for i, (tr,oth) in enumerate(zip(treshold, other)):
    
    data_set1 = np.copy(data_set)
    labels1 = np.copy(labels)
    
    train_data_set_1, test_data_set_1, train_labels_1, test_labels_1 =\
    choose_set_for_label(data_set1, labels1, tr, oth)

    #objects_count = len(train_data_set)
    lambdas, support_vectors, support_vectors_id, b, targets, vector_number =\
    train(train_data_set_1, train_labels_1, kernel_type='rbf')


    predicted = classify_rbf(test_data_set_1, train_data_set_1, lambdas,\
                                                targets, b, vector_number, support_vectors, support_vectors_id)
    predicted = list(predicted.astype(int))
    print("\n-------------------------------------------------------")         
    print("Accuracy for", names[i])
    print("threshold_label = ", tr,", exclude class with id =", oth,":")
    
    print(accuracy_score(predicted, test_labels_1))
    print("-------------------------------------------------------\n")
    print("DONE")

[0 2 1 2 0 0 2 0 0 1 2 0 0 1 2 2 0 1 0 2 2 2 2 1 1 1 0 1 2 2 2 2 0 2 1 2 1
 0 1 0 0 2 1 1 1 1 0 2 2 2 0 1 0 0 2 2 1 1 2 1 0 0 1 1 1 0 2 0 1 0 1 0 2 2
 2 0 1 0 0 1 0 2 2 2 1 0 0 2 0 1 1 2 1 1 1 0 0 2 1 0 2 1 0 2 1 0 0 0 0 2 0
 1 0 0 2 1 2 2 2 2]
(120, 4)
(30, 4)
(120,)
(30,)
(79, 4)
(21, 4)
(79,)
(21,)
[-1  1 -1 -1 -1 -1  1 -1 -1  1 -1  1 -1  1  1  1 -1  1 -1  1  1 -1  1 -1
 -1  1  1  1  1 -1 -1  1 -1 -1  1  1  1 -1 -1  1  1  1 -1 -1  1 -1  1 -1
 -1  1 -1 -1  1 -1  1 -1 -1 -1  1  1  1  1  1 -1 -1  1 -1  1 -1  1 -1 -1
 -1 -1 -1  1 -1 -1  1]
     pcost       dcost       gap    pres   dres
 0:  9.7422e+01 -1.2078e+03  2e+03  1e-01  2e-15
 1:  5.8366e+01 -1.1635e+02  2e+02  5e-03  2e-15
 2:  6.8336e+00 -1.6241e+01  2e+01  8e-16  2e-15
 3: -5.6850e-01 -3.7348e+00  3e+00  3e-16  8e-16
 4: -1.1961e+00 -1.8222e+00  6e-01  2e-16  3e-16
 5: -1.4074e+00 -1.6708e+00  3e-01  2e-16  3e-16
 6: -1.4699e+00 -1.5619e+00  9e-02  2e-16  3e-16
 7: -1.5055e+00 -1.5176e+00  1e-02  2e-16  3e-16
 8: -1.5104e+00